name: etc
on:
  push:
    branches:
      - "*"
    paths:
      - "etc/**"
jobs:
  test:
    name: Test etc
    runs-on: ubuntu-latest
    env:
      DENO_INSTALL: ~/.local
    steps:
      - uses: actions/checkout@master
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh
      - run: $DENO_INSTALL/bin/deno test --allow-net leetcode/etc
