name: LeetCode
on:
  pull_request:
    paths:
      - "leetcode/solutions/**.ts"
jobs:
  test:
    name: Test TypeScript Files
    runs-on: ubuntu-latest
    env:
      DENO_INSTALL: ~/.local
    steps:
      - uses: actions/checkout@v2
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh
      - run: $DENO_INSTALL/bin/deno test --allow-net --allow-env --allow-write leetcode/solutions/*
